<?php

namespace ContainerMJOEhu6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FDYmrUPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FDYmrUP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FDYmrUP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'propertyRepository' => ['privates', 'App\\Repository\\PropertyRepository', 'getPropertyRepositoryService', true],
            'request' => ['privates', '.errored.Xc01EkS', NULL, 'Cannot determine controller argument for "App\\Controller\\PropertyController::index()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'paginator' => '?',
            'propertyRepository' => 'App\\Repository\\PropertyRepository',
            'request' => '?',
        ]);
    }
}
