<?php

namespace ContainerMJOEhu6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PropertyRepository' shared autowired service.
     *
     * @return \App\Repository\PropertyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PropertyRepository'] = new \App\Repository\PropertyRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
