<?php

namespace Container0QhjNsk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertySearchTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PropertySearchType' shared autowired service.
     *
     * @return \App\Form\PropertySearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PropertySearchType'] = new \App\Form\PropertySearchType();
    }
}
