<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYM1eM17\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYM1eM17/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYM1eM17.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYM1eM17\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYM1eM17\App_KernelProdContainer([
    'container.build_hash' => 'YM1eM17',
    'container.build_id' => '966f28e8',
    'container.build_time' => 1600672431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYM1eM17');
