<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin.property.index' => [[], ['_controller' => 'App\\Controller\\AdminPropertyController::index'], [], [['text', '/admin/properties']], [], []],
    'admin.property.edit' => [[], ['_controller' => 'App\\Controller\\AdminPropertyController::edit'], [], [['text', '/admin/edit']], [], []],
    'admin.property.create' => [[], ['_controller' => 'App\\Controller\\AdminPropertyController::create'], [], [['text', '/admin/create']], [], []],
    'admin.property.delete' => [[], ['_controller' => 'App\\Controller\\AdminPropertyController::delete'], [], [['text', '/admin/delete']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'show' => [[], ['_controller' => 'App\\Controller\\HomeController::show'], [], [['text', '/show']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'properties' => [[], ['_controller' => 'App\\Controller\\PropertyController::index'], [], [['text', '/properties']], [], []],
];
