<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNpGbrYw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNpGbrYw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNpGbrYw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNpGbrYw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNpGbrYw\App_KernelDevDebugContainer([
    'container.build_hash' => 'NpGbrYw',
    'container.build_id' => '8bee2127',
    'container.build_time' => 1600678603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNpGbrYw');
