<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHXtbRXm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHXtbRXm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHXtbRXm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHXtbRXm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHXtbRXm\App_KernelDevDebugContainer([
    'container.build_hash' => 'HXtbRXm',
    'container.build_id' => '8324a930',
    'container.build_time' => 1601036645,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHXtbRXm');
