<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Property extends \App\Entity\Property implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'rooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'surface', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'bedrooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'floor', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'heat', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'postal_code', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'sold', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'rooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'surface', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'bedrooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'floor', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'heat', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'address', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'postal_code', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'sold', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Property $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurface(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurface', []);

        return parent::getSurface();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurface(int $surface): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurface', [$surface]);

        return parent::setSurface($surface);
    }

    /**
     * {@inheritDoc}
     */
    public function getRooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRooms', []);

        return parent::getRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setRooms(int $rooms): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRooms', [$rooms]);

        return parent::setRooms($rooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getBedrooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBedrooms', []);

        return parent::getBedrooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setBedrooms(int $bedrooms): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBedrooms', [$bedrooms]);

        return parent::setBedrooms($bedrooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloor(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloor', []);

        return parent::getFloor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloor(int $floor): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloor', [$floor]);

        return parent::setFloor($floor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(int $price): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeat(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeat', []);

        return parent::getHeat();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeat(int $heat): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeat', [$heat]);

        return parent::setHeat($heat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(string $city): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $address): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode(string $postal_code): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postal_code]);

        return parent::setPostalCode($postal_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getSold(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSold', []);

        return parent::getSold();
    }

    /**
     * {@inheritDoc}
     */
    public function setSold(bool $sold): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSold', [$sold]);

        return parent::setSold($sold);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $created_at): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

}
